data:
  preprocess : True
  preprocessMode : 'MinMaxScaler'
  train_test_split : True
  test_train_split_Mode : 'random'
  test_size : 0.1

dataloader:
  _target_: src.dataloader.model
  path: './data/sample/titanic_train.csv'
  target_column: 'target_carbon_monoxide'
  ignore_col : ['date_time' , 'target_benzene' , 'target_nitrogen_oxides'] #['Name', 'Sex', 'Ticket', 'Cabin', 'Embarked']
  fold_id: 0

model:
  _target_: src.models.tabular.tabularmodel
  architecture: "xgboost"
  problem: "regression"
  num_classes: 1
  accelerator: None
  gpus: 1
  max_epochs: 12
  precision: 16

  loss_fn: binary_cross_entropy_with_logits
  lr: 1e-3
  wd: 1e-5

model_config:

wandb:
  _target_: pytorch_lightning.loggers.WandbLogger
  name: "Dogs & Cats"
  project: "Dogs and Cats"

trainer:
  accelerator: None
  gpus: 1
  max_epochs: 12
  precision: 16