# opacity labels consists of what label to output given the opacity tags vector
opacity_labels = {
    "00000": ["label_none"],
    "00001": ["tag_opacity", "label_other"],
    "00010": ["tag_opacity", "tag_fibrosis"],
    "00011": ["tag_opacity", "tag_fibrosis", "label_other"],
    "00100": ["tag_opacity", "tag_consolidation"],
    "00101": ["tag_opacity", "tag_consolidation", "label_other"],
    "00110": ["tag_opacity", "tag_consolidation", "tag_fibrosis"],
    "00111": ["tag_opacity", "label_multiple_types"],
    "01000": ["tag_opacity", "tag_nodule"],
    "01001": ["tag_opacity", "tag_nodule", "label_other"],
    "01010": ["tag_opacity", "tag_nodule", "tag_fibrosis"],
    "01011": ["tag_opacity", "label_multiple_types"],
    "01100": ["tag_opacity", "tag_nodule", "tag_consolidation"],
    "01101": ["tag_opacity", "label_multiple_types"],
    "01110": ["tag_opacity", "label_multiple_types"],
    "01111": ["tag_opacity", "label_multiple_types"],
    "10000": ["tag_opacity", "label_other"],
    "10001": ["tag_opacity", "label_other"],
    "10010": ["tag_opacity", "tag_fibrosis"],
    "10011": ["tag_opacity", "tag_fibrosis", "label_other"],
    "10100": ["tag_opacity", "tag_consolidation"],
    "10101": ["tag_opacity", "tag_consolidation", "label_other"],
    "10110": ["tag_opacity", "tag_consolidation", "tag_fibrosis"],
    "10111": ["tag_opacity", "label_multiple_types"],
    "11000": ["tag_opacity", "tag_nodule"],
    "11001": ["tag_opacity", "tag_nodule", "label_other"],
    "11010": ["tag_opacity", "tag_nodule", "tag_fibrosis"],
    "11011": ["tag_opacity", "label_multiple_types"],
    "11100": ["tag_opacity", "tag_nodule", "tag_consolidation"],
    "11101": ["tag_opacity", "label_multiple_types"],
    "11110": ["tag_opacity", "label_multiple_types"],
    "11111": ["tag_opacity", "label_multiple_types"],
}
